base: 'https://fluidtypo3.org/'
baseVariants:
  -
    base: 'https://legacy.fluidtypo3.org/'
    condition: 'applicationContext == "Production/Staging"'
  -
    base: 'https://fluidtypo3-site.ddev.site/'
    condition: 'applicationContext == "Development"'
dependencies:
  - typo3/fluid-styled-content
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
routeEnhancers:
  FluidshareList:
    type: Extbase
    limitToPages:
      - 6
    extension: Fluidshare
    plugin: Display
    defaultController: 'Gist::list'
    routes:
      -
        routePath: '/context/{tag}/extension/{extension}'
        _controller: 'Gist::list'
        _arguments:
          tag: tag
          extension: extension
      -
        routePath: '/context/{tag}'
        _controller: 'Gist::list'
        _arguments:
          tag: tag
      -
        routePath: '/extension/{extension}'
        _controller: 'Gist::list'
        _arguments:
          extension: extension
    aspects:
      tag:
        type: PersistedAliasMapper
        tableName: tx_fluidshare_domain_model_tag
        routeFieldName: name
      extension:
        type: PersistedAliasMapper
        tableName: tx_fluidshare_domain_model_extension
        routeFieldName: extension_key
  FluidshareDetail:
    type: Extbase
    limitToPages:
      - 9
    extension: Fluidshare
    plugin: Detail
    defaultController: 'Gist::display'
    routes:
      -
        routePath: '/{gist}'
        _controller: 'Gist::display'
        _arguments:
          gist: gist
    aspects:
      gist:
        type: PersistedAliasMapper
        tableName: tx_fluidshare_domain_model_gist
        routeFieldName: slug
  Documentation:
    type: Extbase
    extension: Fluidtypo3org
    plugin: DocDetail
    defaultController: 'Documentation::detail'
    routes:
      -
        routePath: '/{segment1}/{segment2}/{segment3}'
        _controller: 'Documentation::detail'
        _arguments:
          segment1: segment1
          segment2: segment2
          segment3: segment3
      -
        routePath: '/{segment1}/{segment2}'
        _controller: 'Documentation::detail'
        _arguments:
          segment1: segment1
          segment2: segment2
      -
        routePath: '/{segment1}'
        _controller: 'Documentation::detail'
        _arguments:
          segment1: segment1
    requirements:
      segment1: '[a-z0-9]+(?:-[a-z0-9]+)*'
      segment2: '[a-z0-9]+(?:-[a-z0-9]+)*'
      segment3: '[a-z0-9]+(?:-[a-z0-9]+)*'
    aspects:
      segment1:
        type: SafeDocumentationSegmentMapper
      segment2:
        type: SafeDocumentationSegmentMapper
      segment3:
        type: SafeDocumentationSegmentMapper
websiteTitle: ''
